config/routes.rb
Sisfa::Application.routes.draw do
get "dashboard/index"
get "clientes/autocomplete"
get "productos/autocomplete"
get "productos/autocomplete_producto_compra"
get "proveedors/autocomplete"
get "facturas/venta"
get "facturas/index_compra"
get "facturas/index_anulada"
get "dashboard/caducados"
get "dashboard/liquidaciones"
get "dashboard/generar_reporte"
get "dashboard/cierre_de_caja_dia"
get "dashboard/cierre_de_caja_mes"
get "dashboard/reportes_cierre_caja_diario"
get "dashboard/reportes_cierre_caja_mensual"
get "dashboard/estadisticas_dia"
get "dashboard/estadisticas_mes"
get "registros/libro_diario"
get "login"   => "user_sessions#new",        :as => "login"
get "logout"  => "user_sessions#destroy",    :as => "logout"
  
  resources :user_sessions
  resources :users do
    member do
      post "suspender"
    end
  end
  resources :personas
  resources :clientes
  resources :proveedors
  resources :registros
  resources :item_facturas
  resources :item_proformas
  resources :traspasos
  resources :item_traspasos
  resources :hospitalizacions
  resources :item_hospitalizacions
  resources :factura_compras
  resources :canjes do
    member do
      get "nuevo"
      post "save_nuevo" 
    end
  end
  resources :productos do
    resources :kardexes, :as => "kardex"
  end

  resources :facturas do
    member do
      post "anular"
    end
  end

  resources :proformas do
    member do
      post "facturar"
    end
  end

   root 'dashboard#index'

end

app/models/cliente.rb
# == Schema Information
#
# Table name: clientes
#
#  id                       :integer          not null, primary key
#  nombre                   :string(255)
#  direccion                :string(255)
#  numero_de_identificacion :string(255)
#  telefono                 :string(255)
#  email                    :string(255)
#  created_at               :datetime
#  updated_at               :datetime
#  sexo                     :string(255)
#  edad                     :integer
#  estado_civil             :string(255)
#

class Cliente < ActiveRecord::Base

#validations
	validates :nombre, :numero_de_identificacion, :presence =>true
	validates :numero_de_identificacion, :uniqueness => true
	validates_id :numero_de_identificacion, :message => "Cédula incorrecta"
# relationships
	has_one :user
	has_many :proformas
	has_many :facturas
	has_many :registros
	has_many :hospitalizacions
  has_one :cliente_militar
  has_one :militar, through: :cliente_militar

#method

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_filter :require_login
  before_filter :suspendido
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: ClientesDatatable.new(view_context) }
    end
  end

  def autocomplete
    # @cliente= Cliente.new
    respond_to do |format|
      format.json { 
        @clientes = Cliente.where("numero_de_identificacion like ?", "%#{params[:term]}%")
        @clientes = @clientes.map do |cliente|
          {
            :id => cliente.id,
            :label => cliente.numero_de_identificacion + " / " + cliente.nombre,
            :value => cliente.numero_de_identificacion,
            :nombre => cliente.nombre,
            :direccion => cliente.direccion,
            :telefono => cliente.telefono
          }
        end
        render :json => @clientes 
      }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
    respond_to do |format|
      format.js{ render "show" }
    end
  end

  # GET /clientes/new
  def new
    @cliente= Cliente.new
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  # GET /clientes/1/edit
  def edit
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)
    respond_to do |format|
      if @cliente.save
        format.js { 
          render "success"
        }
      else
        format.js{
          render "success"
        }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render action: 'show', status: :created, location: @cliente }
        format.js { render "success"}
      else
        format.html { render action: 'edit' }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
        format.js { render "success"}
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :direccion, :numero_de_identificacion, :telefono, :email)
    end
  end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_clientes.html.erb
<table class="table-bordered data-table" data-source="<%= clientes_url(format: "json") %>">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Cédula o R.U.C</th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th>Email</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    </tbody>
</table>

app/views/clientes/_form.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h1 class="modal-title" id="myModalLabel">Nuevo cliente</h1>
</div>
<%= form_for(@cliente, :remote => true) do |f| %>
<div class="modal-body">
  <div class="field">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, required:true %>
    <%= f.label :numero_de_identificacion, "C.I O RUC" %>
    <%= f.text_field :numero_de_identificacion, required:true%>
    <%= f.label :direccion %>
    <%= f.text_field :direccion %>
    <%= f.label :telefono %>
    <%= f.text_field :telefono %>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
  <%= f.submit 'Guardar', class: "btn btn-primary", :remote => true %>
</div>
<% end %>

app/views/clientes/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h1 class="modal-title" id="myModalLabel">Información</h1>
</div>
<div class="modal-body">
  <p id="notice"><%= notice %></p>
  <p>
    <strong>Nombre:</strong>
    <%= @cliente.nombre %>
  </p>
  <p>
    <strong>Dirección:</strong>
    <%= @cliente.direccion %>
  </p>
  <p>
    <strong>Número de identificación:</strong>
    <%= @cliente.numero_de_identificacion %>
  </p>
  <p>
    <strong>Teléfono:</strong>
    <%= @cliente.telefono %>
  </p>
  <p>
    <strong>Email:</strong>
    <a href="mailto:"><%= @cliente.email%></a>
  </p>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Salir</button>
  <%= link_to 'Editar', edit_cliente_path(cliente), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal', class: "editar_edit"}%>
</div>

app/views/clientes/index.html.erb
<%= link_to 'Nuevo', new_cliente_path,  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal', class: "nuevo_new"}  %>
<h1 class="text-center">Lista de Clientes</h1>

<div class="table-clientes" id="flip-scroll">
  <%= render "clientes", clientes: @clientes %>  
</div>

app/views/clientes/new_or_edit.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'form', locals: {cliente: @cliente}) %>');
window.Helpers.ButtonsHelper.init();
window.Helpers.FormsHelper.init()

app/views/clientes/show.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'show', locals: {cliente: @cliente}) %>');
window.Helpers.ButtonsHelper.init();
window.Helpers.FormsHelper.init()

app/views/clientes/success.js.erb
<%- if @cliente.errors.any? %>
  $('#content_modal').html('<%= escape_javascript(render('form')) %>');
  window.Helpers.ButtonsHelper.init();
  window.Helpers.FormsHelper.init()
  <%- @cliente.errors.full_messages.each do |msg|%>
    alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
  $("#myModal").modal("hide");
  $('body').removeClass('modal-open');
  $('.modal-backdrop').remove();
  $(".table-clientes").html('<%= j render 'clientes', clientes: @clientes %>');
  window.Helpers.init_datatables();
  window.Helpers.ButtonsHelper.init();
  window.Helpers.FormsHelper.init()
  alertify.success("Cliente guardado");
  $(".direccion").val("<%=j @cliente.direccion %>");
  $(".cliente_id").val("<%=j @cliente.id.to_s %>");
  $(".nombre").val("<%=j @cliente.nombre %>");
  $(".telefono").val("<%=j @cliente.telefono %>");
  $(".numero_de_identificacion").val("<%=j @cliente.numero_de_identificacion %>");
<%- end %>