config/routes.rb
Sisfa::Application.routes.draw do
get "dashboard/index"
get "clientes/autocomplete"
get "productos/autocomplete"
get "productos/autocomplete_producto_compra"
get "proveedors/autocomplete"
get "facturas/venta"
get "facturas/index_compra"
get "facturas/index_anulada"
get "dashboard/caducados"
get "dashboard/liquidaciones"
get "dashboard/generar_reporte"
get "dashboard/cierre_de_caja_dia"
get "dashboard/cierre_de_caja_mes"
get "dashboard/reportes_cierre_caja_diario"
get "dashboard/reportes_cierre_caja_mensual"
get "dashboard/estadisticas_dia"
get "dashboard/estadisticas_mes"
get "registros/libro_diario"
get "login"   => "user_sessions#new",        :as => "login"
get "logout"  => "user_sessions#destroy",    :as => "logout"
  
  resources :user_sessions
  resources :users do
    member do
      post "suspender"
    end
  end
  resources :personas
  resources :clientes
  resources :proveedors
  resources :registros
  resources :item_facturas
  resources :item_proformas
  resources :traspasos
  resources :item_traspasos
  resources :hospitalizacions
  resources :item_hospitalizacions
  resources :factura_compras
  resources :canjes do
    member do
      get "nuevo"
      post "save_nuevo" 
    end
  end
  resources :productos do
    resources :kardexes, :as => "kardex"
  end

  resources :facturas do
    member do
      post "anular"
    end
  end

  resources :proformas do
    member do
      post "facturar"
    end
  end

   root 'dashboard#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :require_login
  before_filter :suspendido
  include DashboardHelper
  
  def index    
    estadisticas_dia
  end

  def estadisticas_dia
    # porcentaje de ventas dia
    estadisticas(Time.now, nil)
    estadisticas_hospitalizados(Time.now, nil)
    estadisticas_transferencias(Time.now, nil)
    @totaldia = @total_ventanilla + @total_hospitalizacion
    num_comprobantes = @cantidad_ventanilla + @cantidad_hospitalizacion + @cantidad_transferencia
    @porcentajedia_ventanilla = regla_de_tres(@cantidad_ventanilla, num_comprobantes)
    @porcentajedia_hospitalizacion = regla_de_tres(@cantidad_hospitalizacion, num_comprobantes)
    @porcentajedia_transferencia = regla_de_tres(@cantidad_transferencia, num_comprobantes)
  end

  def estadisticas_mes
    # porcentaje de ventas mes  
    estadisticas(nil, Time.now)
    estadisticas_hospitalizados(nil, Time.now)
    estadisticas_transferencias(nil, Time.now)
    @totalmes = @total_ventanilla + @total_hospitalizacion + @total_transferencia
    num_comprobantes = @cantidad_ventanilla + @cantidad_hospitalizacion + @cantidad_transferencia
    @porcentajemes_ventanilla = regla_de_tres(@cantidad_ventanilla, num_comprobantes)
    @porcentajemes_hospitalizacion = regla_de_tres(@cantidad_hospitalizacion, num_comprobantes)
    @porcentajemes_transferencia = regla_de_tres(@cantidad_transferencia, num_comprobantes)    
  end

  def generar_reporte
    @start_date = params[:fecha_inicial]
    @end_date = params[:fecha_final]
    @tipo_factura = params[:tipo_factura]
    case @tipo_factura
    when "compra"
      @search = consulta_facturas(@start_date.to_time.beginning_of_day..@end_date.to_time.end_of_day, "compra")
      @cantidad_compra = cantidad_comprobantes(@search)
      @total_compra = valor_total_comprobantes(@search)
    when "venta"
      @search = consulta_facturas(@start_date.to_time.beginning_of_day..@end_date.to_time.end_of_day, "venta")
      @cantidad_ventanilla = cantidad_comprobantes(@search)
      @total_ventanilla = valor_total_comprobantes(@search)
    when "hospitalizacion"
      @search = Hospitalizacion.where(:created_at => @start_date.to_time.beginning_of_day..@end_date.to_time.end_of_day)
    when "transferencia"
      @search = Traspaso.where(:created_at => @start_date.to_time.beginning_of_day..@end_date.to_time.end_of_day)
    end
    
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "reporte", :layout => 'report.html', :template => "dashboard/generar_reporte.html.erb", :orientation => 'Landscape'
      end
      format.js
    end
  end

  def reportes_cierre_caja_diario
    cierres_de_caja("dia", params[:fecha].to_time )
    if @total_ventanilla == 0
      render :template => "results/not_result"
    else
      render :pdf => "reporte", :layout => 'report.html', :template => "dashboard/reportes/pdf_caja_dia.html.erb"
    end
  end

  def reportes_cierre_caja_mensual
    cierres_de_caja("mes", params[:fecha].to_time)
    if @total_ventanilla == 0
      render :template => "results/not_result"
    else
      render :pdf => "reporte", :layout => 'report.html', :template => "dashboard/reportes/pdf_caja_mes.html.erb"
    end
  end

  def liquidaciones
    @fecha = params[:fecha]
    unless @fecha.to_time > Time.now
      cierres_de_caja("mes", @fecha.to_time)
      @anuladas_ventanilla = Factura.where(:created_at => @fecha.to_time.beginning_of_month..@fecha.to_time.end_of_month).where(:anulada => true).count()
      # transferencias
      transferencias = transferencias(@fecha)
      @numero_transferencias = transferencias.count()
      @transferencias_subtotal = transferencias.sum(:subtotal)
      @transferencias_iva = transferencias.sum(:iva)
      @total_transferencias = transferencias.sum(:total)
      # valores de ventas y transferencias
      @subtotal_ventas = @hospitalizacion_subtotal + @ventanilla_subtotal + @transferencias_subtotal
      @iva_ventas = @ventanilla_iva + @hospitalizacion_iva + @transferencias_iva
      @total_ventas = @subtotal_ventas + @iva_ventas
      #valores factura de compra
      @compras = facturas_compra(@fecha.to_time)
      respond_to do |format|
        format.html
        format.pdf do
          render :pdf => "liquidaciones", :locals => { :fecha => @fecha }, :layout => 'report.html', :template => "dashboard/liquidaciones.html.erb", :orientation => 'Landscape'
        end
      end
    else
      render :template => "results/not_result"
    end
  end

  def cierre_de_caja_dia
    cierres_de_caja("dia", Time.now)
    respond_to do |format|
      format.html
      format.js
      format.pdf do
        render :pdf => "reporte", :layout => 'report.html', :template => "dashboard/reportes/pdf_caja_dia.html.erb"
      end
    end
  end

  def cierre_de_caja_mes
    cierres_de_caja("mes", Time.now)
    respond_to do |format|
      format.html
      format.js
      format.pdf do
        render :pdf => "reporte", :layout => 'report.html', :template => "dashboard/reportes/pdf_caja_mes.html.erb"
      end
    end
  end

  def caducados
    @caducados = IngresoProducto.where(:fecha_caducidad =>Time.now.end_of_day..Time.now.months_since(4)).where("cantidad != '0'")
    @hoy = Date.today
    respond_to do |format|
      # format.json { render json: ProductosDatatable.new(view_context, "caducados") }
      format.html
      format.js
    end
    # @caducados = Producto.where(:fecha_de_caducidad =>Time.now.end_of_day..Time.now.months_since(4))
  end

  private

  def estadisticas(dia, mes)
    fecha_dia = dia
    fecha_mes = mes
    if dia
      @facturas = consulta_facturas(fecha_dia.beginning_of_day..fecha_dia.end_of_day,"venta")
    else
      @facturas = consulta_facturas(fecha_mes.beginning_of_month..fecha_mes.end_of_month,"venta")
    end

    @cantidad_ventanilla = cantidad_comprobantes(@facturas)
    @total_ventanilla = valor_total_comprobantes(@facturas)
  end

  def estadisticas_hospitalizados(dia, mes)
    fecha_dia = dia
    fecha_mes = mes
    if dia
      @hospitalizados = consulta_hospitalizacion(fecha_dia.beginning_of_day..fecha_dia.end_of_day)
    else
      @hospitalizados = consulta_hospitalizacion(fecha_mes.beginning_of_month..fecha_mes.end_of_month)
    end

    @cantidad_hospitalizacion = cantidad_comprobantes(@hospitalizados)
    @total_hospitalizacion = valor_total_comprobantes(@hospitalizados)
  end

  def estadisticas_transferencias(dia, mes)
    fecha_dia = dia
    fecha_mes = mes
    if dia
      @transferencias = consulta_transferencias(fecha_dia.beginning_of_day..fecha_dia.end_of_day)
    else
      @transferencias = consulta_transferencias(fecha_mes.beginning_of_month..fecha_mes.end_of_month)
    end
    @cantidad_transferencia = cantidad_comprobantes(@transferencias)
    @total_transferencia = valor_total_comprobantes(@transferencias)
  end

  def cierres_de_caja(periodo, fecha)
    if periodo == "dia"
      estadisticas(fecha, nil)
      @ventanilla_subtotal = sumar_impuesto(@facturas, "subtotal_0")
      @ventanilla_iva = sumar_impuesto(@facturas, "iva")
    else
      estadisticas(nil, fecha)
      estadisticas_hospitalizados(nil, fecha)
      estadisticas_transferencias(nil, fecha)
      @ventanilla_subtotal = sumar_impuesto(@facturas, "subtotal_0")
      @hospitalizacion_subtotal = sumar_impuesto(@hospitalizados, "subtotal")
      @transferencia_subtotal = sumar_impuesto(@transferencias, "subtotal")
      @total_subtotal = @ventanilla_subtotal + @hospitalizacion_subtotal + @transferencia_subtotal
      @ventanilla_iva = sumar_impuesto(@facturas, "iva")
      @hospitalizacion_iva = sumar_impuesto(@hospitalizados, "iva")
      @transferencia_iva = sumar_impuesto(@transferencias, "iva")
      @total_iva = @ventanilla_iva + @hospitalizacion_iva + @transferencia_iva
      @num_comprobantes = @cantidad_ventanilla + @cantidad_hospitalizacion
      @totaldia = @total_ventanilla + @total_hospitalizacion + @total_transferencia
    end
  end

  def consulta_facturas(fecha, tipo)
    case current_user.rol
    when Rol.administrador
      todasfacturas = Factura.where(:created_at => fecha, :tipo => tipo, :anulada => false)
    when Rol.vendedor
      todasfacturas = Factura.where(:created_at => fecha, :user_id => current_user.id, :anulada => false)
    end
    return :json => todasfacturas
  end

  def consulta_hospitalizacion(fecha)
    case current_user.rol
    when Rol.administrador
      hospitalizados = Hospitalizacion.where(:created_at => fecha)
    when Rol.vendedor
      hospitalizados = Hospitalizacion.where(:created_at => fecha, :user_id => current_user.id)
    end
    return :json => hospitalizados
  end

  def consulta_transferencias(fecha)
    case current_user.rol
    when Rol.administrador
      transferencias = Traspaso.where(:created_at => fecha)
    when Rol.vendedor
      transferencias = Traspaso.where(:created_at => fecha, :user_id => current_user.id)
    end
    return :json => transferencias
  end

  def transferencias(fecha)
    fecha = fecha.to_time
    traspasos = Traspaso.where(:created_at => fecha.beginning_of_month..fecha.end_of_month)
  end

  def facturas_compra(fecha)
    facturas = FacturaCompra.where(:created_at => fecha.beginning_of_month..fecha.end_of_month)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	def regla_de_tres (comprobante, total_comprobantes)
    if total_comprobantes == 0
      porcentaje = 0        
    else
      porcentaje = (100.0 * comprobante)/total_comprobantes
    end
    return porcentaje
  end

  def cantidad_comprobantes(comprobante)
    cantidad = 0
    comprobante.each do |value, key|
      key.each do |comprobante|
        cantidad += 1
      end
    end
    return cantidad
  end

  def valor_total_comprobantes(comprobante)
    total = 0
    comprobante.each do |value, key|
      key.each do |comprobante|
          total += comprobante.total
      end
    end
    return total
  end

  def sumar_impuesto (comprobantes, tipo_impuesto)
    impuesto = tipo_impuesto
    sumar = 0
    comprobantes.each do |value, key|
      key.each do |comprobante|
        case impuesto
        when 'iva'
          sumar += comprobante.iva
        when 'subtotal_0'
          sumar += comprobante.subtotal_0
        when 'subtotal'
          sumar += comprobante.subtotal
        when 'subtotal_12'
          sumar += comprobante.subtotal_12
        when 'descuento'
          sumar += comprobante.descuento
        end
        sumar
      end
    end
    return sumar
  end
end

app/views/dashboard/_caducados.html.erb
<div class="container">
  <div class="row">
    <h3 class="fix-margin">Productos Por Caducar</h3>
    <% @caducados.each do |caduco|  %>
    <div class="col-md-4">
      <div class="blockquote-box blockquote-danger clearfix">
        <div class="thumbnail square pull-left">
          <div class="caption only-admin">
            <h5>Hacer Canje</h5>
            <i class ="fa fa-share-square-o fa-2x"></i><br/>
            <%= link_to "Canje", nuevo_canje_path(caduco), :class => "label label-default" %>
          </div>
          <span class="fa-3x"><%= caduco.producto.nombre.chr.upcase %></span>
        </div>
        <h4><%= caduco.producto.nombre %> /  <%= caduco.producto.casa_comercial %></h4>
        <h5>Cantidad: <%= caduco.cantidad %></h5>
        <h5>Fecha: <%= caduco.fecha_caducidad %></h5>
        <h6 class ="text-muted">El producto se caducará en: <strong class="days"><%=(caduco.fecha_caducidad - @hoy ).to_i%></strong> dias</h6>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/dashboard/_caja_dia_o_mes.html.erb
<% if  @totalfacturas == 0  and @totalhospitalizacion == 0 %>
  <h3>No has facturado nada Aun!..</h3>
<% else %>
<table class="table table-hover table-print">
    <thead>
      <tr>
        <th></th>
        <th>VENTANILLA</th>
        <th>HOSPITALIZACIÓN</th>
        <th>TRANSFERENCIA</th>
        <th>TOTAL</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Facturas:</td>
        <td><%= @cantidad_ventanilla %></td>
        <td><%= @cantidad_hospitalizacion %></td>
        <td><%= @cantidad_transferencia %></td>
        <td><%= @num_comprobantes %></td>
      </tr>
      <tr>
        <td>Subtotal:</td>
        <td><%= redondear(@ventanilla_subtotal) %></td>
        <td><%= redondear(@hospitalizacion_subtotal) %></td>
        <td><%= redondear(@transferencia_subtotal) %></td>
        <td><%= redondear(@total_subtotal) %></td>
      </tr>
      <tr>
        <td>Iva:</td>
        <td><%= redondear(@ventanilla_iva) %></td>
        <td><%= redondear(@hospitalizacion_iva) %></td>
        <td><%= redondear(@transferencia_iva) %></td>
        <td><%= redondear(@total_iva) %></td>
      </tr>
      <tr>
        <td>Total:</td>
        <td><%= redondear(@total_ventanilla) %></td>
        <td><%= redondear(@total_hospitalizacion) %></td>
        <td><%= redondear(@total_transferencia) %></td>
        <td><strong><%= redondear(@totaldia) %></strong></td>
      </tr>
    </tbody>
</table>
<% end %>

app/views/dashboard/_reporte.html.erb
<div class="row col-md-8 estadisticas" id="reportes">
	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Ventas y Compras</h3>
			</div><!-- end panel-heading -->	
			<div class="panel-body">
				<%= form_tag dashboard_generar_reporte_path, method: :get do %>
				<%= select_tag :tipo_factura, "<option value='venta'>Ventanilla</option><option value='hospitalizacion'>Hospitalización</option><option value='compra'>Compra</option><option value='transferencia'>Transferencias</option>".html_safe, { :class => "col-md-4 form-control selecttag" } %> <br />	
				<span class="fa fa-calendar"></span>
				<%= text_field_tag :fecha_inicial, params[:fecha_inicial], :class => "form-control-border datepicker", placeholder: "Fecha de inicio", :required => true %><br><br>
				<span class="fa fa-calendar"></span>
				<%= text_field_tag :fecha_final, params[:fecha_final], :class => "form-control-border datepicker", placeholder: "Fecha final", :required => true %><br><br>
				<%= submit_tag "Imprimir", :class => "btn btn-block btn-info", format: :pdf%>
				<% end %>
			</div>
		</div><!-- end panel -->
	</div><!-- end venta y compra -->
	<div class="col-sm-4 only-admin">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Cierre de Caja</h3>
			</div><!-- end panel-heading -->
			<div class="panel-body">												
				<h5>Ingrese Fecha (mes):</h5>
				<%= form_tag dashboard_reportes_cierre_caja_mensual_path, method: :get do %>
				<div class="input-group field">
					<%= text_field_tag :fecha, params[:fecha],:class =>" datepicker_month", :placeholder => "Fecha", :required => true%>
					<span class="input-group-btn">
						<%= submit_tag "Ir", name: nil, :class => "btn btn-info" %>
					</span>
				</div>
				<% end %>
				<h5>Ingrese Fecha (dia):</h5>
				<%= form_tag dashboard_reportes_cierre_caja_diario_path, method: :get do %>
				<div class="input-group field">
					<%= text_field_tag :fecha, params[:fecha],:class =>"datepicker", :placeholder => "Fecha", :required => true%>
					<span class="input-group-btn">
						<%= submit_tag "Ir", name: nil, :class => "btn btn-info" %>
					</span>
				</div>
				<% end %>
			</div>
		</div><!-- end panel -->
	</div><!-- end cierre de caja -->
	<div class="col-sm-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title">Liquidaciones</h3>
			</div><!-- end panel-heading -->
			<div class="panel-body">																
				<h5>Ingrese Mes:</h5>
				<%= form_tag dashboard_liquidaciones_path, method: :get do %>
				<div class="input-group field">
					<%= text_field_tag :fecha, params[:fecha],:class =>"datepicker_month", :placeholder => "Fecha", :required => true%>
					<span class="input-group-btn">
						<%= submit_tag "Ir", name: nil, :class => "btn btn-info" %>
					</span>
				</div>
				<% end %>
			</div>
		</div><!-- end panel -->
	</div><!-- end liquidaciones -->
</div>

app/views/dashboard/caducados.js.erb
$(".tab-content").html("<%= j render('caducados') %>");
window.Helpers.ButtonsHelper.init();
window.Helpers.DateHelper.init();
window.Helpers.HiddenContent.init();

app/views/dashboard/cierre_de_caja_dia.js.erb
m = $('#content_modal');
m.html('<%= j render("dashboard/cierre_dia/modal") %>');
window.Helpers.ButtonsHelper.init();

app/views/dashboard/cierre_de_caja_mes.js.erb
m = $('#content_modal');
m.html('<%= j render("dashboard/cierre_mes/modal") %>');
window.Helpers.ButtonsHelper.init();
window.Helpers.HiddenContent.init();

app/views/dashboard/estadisticas_dia.js.erb
$(".tab-content").html("<%= j render('dashboard/cierre_dia/diario') %>");
window.Helpers.ButtonsHelper.init();
window.Helpers.DateHelper.init();

app/views/dashboard/estadisticas_mes.js.erb
$(".tab-content").html("<%= j render('dashboard/cierre_mes/mensual') %>");
window.Helpers.ButtonsHelper.init();
window.Helpers.DateHelper.init();

app/views/dashboard/generar_reporte.html.erb
<%= link_to ' Imprimir', {:format => :pdf} , {:target => "_blank"} %>
<% if @search == 0 %>
  <h3>No se encontro ninguna factura</h3>
<% else %>
  <%case @tipo_factura%>
    <%when "venta"%>
    <h3>Reporte de Facturas  de Ventanilla  desde:</h3>
    <h4><%= @start_date%> hasta <%= @end_date%></h4>
    <table class="table table-hover table-print">
      <thead>
        <tr>
          <th>Nº Factura</th>
          <th>Cliente</th>
          <th>Dirección</th>
          <th>Vendedor</th>
          <th>Fecha</th>
          <th>Sub Total</th>
          <th>IVA</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
      <% @search.each do |value, key|  %>
        <% key.each do |factura| %>
          <tr>
            <td><%= factura.numero %></td>
            <td><%= factura.cliente.nombre %></td>
            <td><%= factura.cliente.direccion %></td>
            <td><%= factura.user.username %></td>
            <td><%= local_date(factura.created_at,"datetime") %></td>
            <td><%= factura.subtotal_0 %></td>
            <td><%= factura.iva %></td>
            <td><%= factura.total %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
    <h4>Facturas Emitidas: <%= @cantidad_ventanilla%> </h4>
    <h4>Total de Venta: <%= redondear(@total_ventanilla) %> </h4>
  <%when "hospitalizacion"%>
    <h3>Reporte de Ventas de Hospitalización desde:</h3>
    <h4><%= @start_date%> hasta <%= @end_date%></h4>
    <table class="table table-hover table-print">
      <thead>
        <tr>
          <th>Nº</th>
          <th>Cliente</th>
          <th>Dirección</th>
          <th>Servicio</th>
          <th>Rango</th>
          <th>Vendedor</th>
          <th>Fecha</th>
          <th>Sub Total</th>
          <th>IVA</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <% @search.each do |h| %>
        <tr>
          <td><%= h.numero %></td>
          <td><%= h.cliente.nombre%></td>
          <td><%= h.cliente.direccion %></td>
          <td>ninguno</td>
          <td>ninguno</td>
          <td><%= h.user.username %></td>
          <td><%= local_date(h.created_at,"datetime") %></td>
          <td><%= redondear(h.subtotal) %></td>
          <td><%= redondear(h.iva) %></td>
          <td><%= redondear(h.total) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <h4>Comprobantes Emitidos: <%= @search.count%></h4>
    <h4>Total de Venta: <%= redondear(@search.sum(:total)) %></h4>
  <%when "compra"%>
    <h3>Reporte de Facturas  de Compra  desde:</h3>
    <h4><%= @start_date%> hasta <%= @end_date%></h4>
    <table class="table table-hover table-print">
      <thead>
        <tr>
          <th>Nº Factura</th>
          <th>Proveedor o casa comercial</th>
          <th>Dirección</th>
          <th>Registrado por</th>
          <th>Fecha</th>
          <th>Sub Total</th>
          <th>IVA</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
      <% @search.each do |value, key|  %>
        <% key.each do |factura| %>
          <tr>
            <td><%= factura.numero %></td>
            <td><%= factura.proveedor.nombre_o_razon_social %></td>
            <td><%= factura.proveedor.direccion %></td>
            <td><%= factura.user.username %></td>
            <td><%= local_date(factura.created_at,"datetime") %></td>
            <td><%= factura.subtotal_0 %></td>
            <td><%= factura.iva %></td>
            <td><%= factura.total %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
    <h4>Comprobantes Ingressados: <%= @cantidad_compra%> </h4>
    <h4>Total de Compras: <%= @total_compra %> </h4>
  <%when "transferencia"%>
    <h3>Reporte de Transferencias desde:</h3>
    <h4><%= @start_date%> hasta <%= @end_date%></h4>
    <table class="table table-hover table-print">
      <thead>
        <tr>
          <th>Nº</th>
          <th>Tansferencia a</th>
          <th>Emitido por</th>
          <th>Entregado a</th>
          <th>Fecha y Hora</th>
          <th>Sub Total</th>
          <th>IVA</th>
          <th>Total</th>
        </tr>
      </thead>
      <tbody>
        <% @search.each do |t| %>
        <tr>
          <td><%= t.numero %></td>
          <td><%= t.servicio%></td>
          <td><%= t.user.username %></td>
          <td><%= t.entregado_a%></td>
          <td><%= local_date(t.created_at,"datetime") %></td>
          <td><%= redondear(t.subtotal)%></td>
          <td><%= redondear(t.iva) %></td>
          <td><%= redondear(t.total) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    <h4>Total de Transferencias: <%= @search.count%> </h4>
    <h4>Total de Venta: <%= redondear(@search.sum(:total)) %></h4>
    <% end %>
<% end %>

app/views/dashboard/generar_reporte.js.erb
$(".tab-content").html("<%= j render('reporte') %>");
window.Helpers.ButtonsHelper.init();
window.Helpers.DateHelper.init();
window.Helpers.Datepicker.init_datepicker();
window.Helpers.Datepicker.init_datepicker_month();
window.Helpers.FormsHelper.init();

app/views/dashboard/index.html.erb
<h1 class= "text-center"><span class="fa fa-bar-chart-o"></span> Estadísticas</h1>
<ul class="nav nav-tabs" id="tab_estadisticas">
  <li class="active"><%=link_to "Diario",{:controller => 'dashboard', :action => 'estadisticas_dia'}, :remote => true, :data => {:toogle => "tab"} %></li>
  <li><%=link_to "Mes",{:controller => 'dashboard', :action => 'estadisticas_mes'}, :remote => true, :data => {:toogle => "tab"} %></li>
  <li><%=link_to "Reportes",{:controller => 'dashboard', :action => 'generar_reporte'}, :remote => true, :data => {:toogle => "tab"}, :class => "only-admin" %></li>
  <li><%=link_to "Caducados",{:controller => 'dashboard', :action => 'caducados'}, :remote => true, :data => {:toogle => "tab"}, :class => "on" %></li>
</ul>

<div class="tab-content">
  <%= render "dashboard/cierre_dia/diario"%>
</div>

<%= javascript_tag "window.Helpers.NavbarVentas.init_estadisticas();" %>