config/routes.rb
Sisfa::Application.routes.draw do
get "dashboard/index"
get "clientes/autocomplete"
get "productos/autocomplete"
get "productos/autocomplete_producto_compra"
get "proveedors/autocomplete"
get "facturas/venta"
get "facturas/index_compra"
get "facturas/index_anulada"
get "dashboard/caducados"
get "dashboard/liquidaciones"
get "dashboard/generar_reporte"
get "dashboard/cierre_de_caja_dia"
get "dashboard/cierre_de_caja_mes"
get "dashboard/reportes_cierre_caja_diario"
get "dashboard/reportes_cierre_caja_mensual"
get "dashboard/estadisticas_dia"
get "dashboard/estadisticas_mes"
get "registros/libro_diario"
get "login"   => "user_sessions#new",        :as => "login"
get "logout"  => "user_sessions#destroy",    :as => "logout"
  
  resources :user_sessions
  resources :users do
    member do
      post "suspender"
    end
  end
  resources :personas
  resources :clientes
  resources :proveedors
  resources :registros
  resources :item_facturas
  resources :item_proformas
  resources :traspasos
  resources :item_traspasos
  resources :hospitalizacions
  resources :item_hospitalizacions
  resources :factura_compras
  resources :canjes do
    member do
      get "nuevo"
      post "save_nuevo" 
    end
  end
  resources :productos do
    resources :kardexes, :as => "kardex"
  end

  resources :facturas do
    member do
      post "anular"
    end
  end

  resources :proformas do
    member do
      post "facturar"
    end
  end

   root 'dashboard#index'

end

app/models/traspaso.rb
# == Schema Information
#
# Table name: traspasos
#
#  id            :integer          not null, primary key
#  servicio      :string(255)
#  fecha_emision :date             not null
#  numero        :integer          not null
#  iva           :float            not null
#  total         :float            not null
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  subtotal      :float            not null
#  entregado_a   :string(255)
#

class Traspaso < ActiveRecord::Base
	has_many :item_traspasos
	has_many :ingreso_productos, :through => :item_traspasos
  belongs_to :user

	accepts_nested_attributes_for :item_traspasos

	#validations
  validates :servicio, :user_id, :numero, :iva, :total,:fecha_emision, :entregado_a, presence: true
  validates :total, :numericality => { :greater_than_or_equal_to => 0}
  validates :numero, :numericality => { only_integer: true }

	#methods
	item_traspasos = []
	def self.disminuir_stock (item_traspasos)
		item_traspasos.each do |item|
			unless item.producto_id.nil?
				producto  = Producto.find(item.producto_id)
				producto.cantidad_disponible -= item.cantidad
				producto.save
			end
		end
	end
end

app/controllers/traspasos_controller.rb
class TraspasosController < ApplicationController
  before_filter :suspendido

	 def index
    respond_to do |format|
      format.html
      format.json { render json: TraspasosDatatable.new(view_context) }
    end
  end

	def new
		@traspaso = Traspaso.new
		@traspaso.item_traspasos.build
		respond_to do |format|
      format.html
      format.js
    end
	end

	def create
		respond_to do |format|
			@traspaso = Traspaso.new(traspaso_params)
			@traspaso.numero = Traspaso.last ? Traspaso.last.numero + 1 : 1
			@traspaso.fecha_emision = Time.now
			@traspaso.user_id = current_user.id
			@traspaso.save
  		format.js
		end	
	end

	def show
		@traspaso = Traspaso.find(params[:id])
		respond_to do |format|
      format.js
      format.pdf do
				render :pdf => "proforma", :layout => 'report.html', :template => "traspasos/traspaso_pdf.html.erb"
			end
    end
	end

	private

	def traspaso_params
		params.require(:traspaso).permit :servicio,
		:fecha_emision,
		:numero,
		:subtotal,
		:iva,
		:total,
		:user_id,
		:entregado_a,
		:item_traspasos_attributes => [
			:cantidad,
			:valor_unitario,
			:iva,
			:total,
			:ingreso_producto_id
		]
	end
	
end

app/helpers/traspasos_helper.rb
module TraspasosHelper
end

app/views/traspasos/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h1 class="modal-title" id="myModalLabel">Información</h1>
</div>
<div class="modal-body">
	 <p>
    <strong>Dependencia:</strong>
    <%= @traspaso.servicio%>
  </p>
  <p>
    <strong>Fecha de Emisión:</strong>
    <%= @traspaso.fecha_emision %>
  </p>
  <table class="table table-hover">
	  <thead class= "well">
	    <tr>
	      <th>Producto</th>
	      <th>Cantidad</th>
	      <th>Precio</th>
	      <th>Iva</th>
	      <th>Total</th>
	    </tr>
	  </thead>
	  <tbody>
	    <% @traspaso.item_traspasos.each do |t| %>
	      <tr>
	        <td><%= t.ingreso_producto.producto.nombre%></td>
	        <td><%= t.cantidad %></td>
	        <td>$ <%= t.valor_unitario %></td>
	        <td>$ <%= t.iva %></td>
	        <td>$ <%= t.total %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
  <h4 class="text-success text-right">
    <strong>Total: $</strong>
    <%= @traspaso.total %>
  </h4>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Salir</button>
</div>

app/views/traspasos/create.js.erb
<%- if @traspaso.errors.any? %>
  <%- @traspaso.errors.full_messages.each do |msg|%>
      alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
  $.getScript("/traspasos/<%= @traspaso.id%>");
  $('#myModal').modal({
    remote: ""
  });
  $('#myModal').on("shown.bs.modal", function() {
    $('.modal-footer').html('<a class="print_button looks_like_button btn btn-info" href="/traspasos/<%= @traspaso.id%>.pdf" target="_blank"><i class="fa fa-print"></i>  Imprimir</a>')
  });
  alertify.success("Transferencia Guardada");
<%- end %>

app/views/traspasos/index.html.erb
<%= link_to 'Nueva', new_traspaso_path, class: "nuevo_new"  %>
<h1 class="text-center">LISTA DE TRANSFERENCIAS</h1>
<div class=" col-md-10 col-md-offset-1 table-responsive">
	<table class="data-table table-bordered" data-source="<%= traspasos_url(format: "json") %>">
		<thead>
			<tr>
				<th>Número</th>
				<th>Dependencia</th>
				<th>Emitido por</th>
				<th>Recibido por</th>
				<th>Fecha</th>
				<th>Acciones</th>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>

app/views/traspasos/new.html.erb
<div class="col-md-7">
	<legend>Tansferencia Interna de Productos</legend>
</div>
<div class="container">
	<%= nested_form_for @traspaso, :remote => true do |f| %>
	<%= form_errors_for @traspaso %>
	<div class="row">
		<div class="col-md-8">
			<div class="panel panel-default">
				<div class="panel-heading">
					<div class="panel-title">
						<div class="row">
							<div class="col-md-6 col-sm-12">
								<%= f.select :servicio, options_for_select(["Medicina Interna","Cardiología","Ginecología","Gastroenterología","Dermatología","Rayos X","Farmacia","Central de Enfermería","Estadística","Financiero","Traumatología","Odontología","Laboratorio Clínico","Fisiatría","Pediatría"]), {}, { class: "select-servicio"}%>
							</div>
							<div class ="col-md-6">
								<%= f.text_field :entregado_a, :class => "form-control",:placeholder => "Entregado a:" %>
							</div>
						</div>
					</div>
				</div>
				<div class="panel-body">
					<table class="table">
						<thead class = "text-center">
							<th>Image</th>
							<th>Producto</th>
							<th>V.Unit</th>
							<th>Iva</th>
							<th>Cantidad</th>
							<th>Total</th>		
							<th></th>		
						</thead>
						<tbody>
							<%= f.fields_for :item_traspasos, :wrapper => false do |b| %>
							<tr class="fields productos_traspaso">
								<%= render 'item_traspasos/item_traspaso', f: b %>
								<% end %>
							</tr>
							<tr>
								<td>
									<%= f.link_to_add "Producto", :item_traspasos, :class => "nuevo_new"%>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="panel-footer">
					<div class="row text-center">
						<div class="col-md-9">
							<%= f.hidden_field :subtotal, class: "subtotal_traspaso" %>
							<%= f.hidden_field :total, class: "total_traspaso" %>
							<%= f.hidden_field :iva, class: "iva_traspaso" %>
							<h4 class="text-right">Total <strong class= "total">$00.00</strong></h4>
						</div>
						<div class="col-md-3">
							<%= f.submit :Guardar, class: " btn btn-block guardar_submit", data: {disable_with: "Almacenando"}%>			
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<div>
		<%= link_to "Todas las transferencias", traspasos_path, class: "atras_back" %>
	</div>
</div>

app/views/traspasos/show.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'show', locals: {trasferencia: @trasferencia}) %>');
window.Helpers.ButtonsHelper.init();

app/views/traspasos/traspaso_pdf.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-6">
			<h3>TRANSFERENCIA #<%= @traspaso.numero%></h3>
			<h5>Dependencia: <%= @traspaso.servicio%></h5>
			<h6>Emitido por: <%= @traspaso.user.username%></h6>
			<h6>Entregado a: <%= @traspaso.entregado_a%></h6>
			<h6>Fecha de emision: <%= @traspaso.fecha_emision %></h6>
		</div>
		<div class="col-xs-6 text-right">			
				<h3>HOSPITAL BASICO 7 B.I<h3>
				<h6>Correo: hb7loja2012@gmail.com</h6>
				<h6>Telefono: (07) 257-0254</h6>
				<h6 class="text-muted">*Documento de uso interno</h6>
			</div>
		</div>
		<table class="table table-bordered">
			<thead class="well">
				<tr>
					<th>Producto</th>
					<th>Cantidad</th>
					<th>Precio</th>
					<th>Iva</th>
					<th>Total</th>
				</tr>
			</thead>
			<tbody>
				<% @traspaso.item_traspasos.each do |item| %>
				<tr>
					<td><%= item.ingreso_producto.producto.nombre%></td>
					<td><%= item.cantidad %></td>
					<td><%= item.valor_unitario %></td>
					<td><%= item.iva%></td>
					<td class="text-right"><%= item.total %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<div class="row text-right">
			<div class="col-xs-2 col-xs-offset-8">
				<p>
					<strong>
						Sub Total : <br>
						IVA : <br>
						Total : <br>
					</strong>
				</p>
			</div>
			<div class="col-xs-2">
				<strong>
					$ <%= @traspaso.subtotal %><br>
					$ <%= @traspaso.iva %><br>
					$ <%= @traspaso.total %><br>
				</strong>
			</div>
		</div>
	</div>
</div>