config/routes.rb
Sisfa::Application.routes.draw do
get "dashboard/index"
get "clientes/autocomplete"
get "productos/autocomplete"
get "productos/autocomplete_producto_compra"
get "proveedors/autocomplete"
get "facturas/venta"
get "facturas/index_compra"
get "facturas/index_anulada"
get "dashboard/caducados"
get "dashboard/liquidaciones"
get "dashboard/generar_reporte"
get "dashboard/cierre_de_caja_dia"
get "dashboard/cierre_de_caja_mes"
get "dashboard/reportes_cierre_caja_diario"
get "dashboard/reportes_cierre_caja_mensual"
get "dashboard/estadisticas_dia"
get "dashboard/estadisticas_mes"
get "registros/libro_diario"
get "login"   => "user_sessions#new",        :as => "login"
get "logout"  => "user_sessions#destroy",    :as => "logout"
  
  resources :user_sessions
  resources :users do
    member do
      post "suspender"
    end
  end
  resources :personas
  resources :clientes
  resources :proveedors
  resources :registros
  resources :item_facturas
  resources :item_proformas
  resources :traspasos
  resources :item_traspasos
  resources :hospitalizacions
  resources :item_hospitalizacions
  resources :factura_compras
  resources :canjes do
    member do
      get "nuevo"
      post "save_nuevo" 
    end
  end
  resources :productos do
    resources :kardexes, :as => "kardex"
  end

  resources :facturas do
    member do
      post "anular"
    end
  end

  resources :proformas do
    member do
      post "facturar"
    end
  end

   root 'dashboard#index'

end

app/models/producto.rb
# == Schema Information
#
# Table name: productos
#
#  id              :integer          not null, primary key
#  nombre          :string(255)      not null
#  codigo          :string(255)
#  categoria       :string(255)
#  casa_comercial  :string(255)
#  nombre_generico :string(255)
#  precio_compra   :decimal(4, 2)    not null
#  precio_venta    :decimal(4, 2)    not null
#  ganancia        :decimal(4, 2)    not null
#  hasiva          :boolean          default(FALSE)
#

class Producto < ActiveRecord::Base

#callbacks 
  before_create :set_precios
  before_update :set_precios
  after_create :set_kardex

#validations  
  validates :nombre, :ganancia, :precio_compra, :presence => true
  validates :nombre, :length => { :maximum => 100 }
 
#relations
  has_many :ingreso_productos
  has_one :kardex
  has_many :factura_compras_productos
  has_many :factura_compras, :through => :factura_compras_productos
  has_many :canjes

#nested
  accepts_nested_attributes_for :ingreso_productos, :allow_destroy => true, reject_if: :all_blank

#methods

  def cantidad_disponible
    unless self.ingreso_productos.empty? then self.ingreso_productos.sum(:cantidad) else 0 end
  end

  private
  def set_kardex
    Kardex.create(:producto => self, :fecha => Time.now)
  end

  def set_precios
    self.precio_venta = self.precio_compra * self.ganancia/100 + self.precio_compra
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
	before_filter :require_login
  before_filter :suspendido
  before_action :set_producto, only: [:show, :edit, :update]
  def index
    respond_to do |format|
      format.html
      format.json { render json: ProductosDatatable.new(view_context) }
    end
  end

  def autocomplete
    # @producto = Producto.new
    respond_to do |format|
      format.json { 
        @productos = IngresoProducto.includes(:producto).where("cantidad != 0 and productos.nombre like ?", "%#{params[:term]}%").references(:producto)
        @productos = @productos.map do |ingreso|
          {
            :id => ingreso.producto.id,
            :label => ingreso.producto.nombre + "/" + "LT:" + ingreso.lote ,
            :value => ingreso.producto.nombre,
            :precio_venta => ingreso.producto.precio_venta,
            :id_ingreso => ingreso.id,
            :iva => ingreso.producto.hasiva,
            :casa_comercial => ingreso.producto.casa_comercial
          }
        end
        render :json => @productos 
      }
    end    
  end

  def autocomplete_producto_compra
    respond_to do |format|
      format.json { 
        @productos = Producto.where("nombre like ?", "%#{params[:term]}%")
        @productos = @productos.map do |producto|
          {
            :id => producto.id,
            :label => producto.nombre + " / " + producto.casa_comercial ,
            :value => producto.nombre,
            :precio_venta => producto.precio_venta,
            :precio_compra => producto.precio_compra,
            :ganancia => producto.ganancia,
            :codigo => producto.codigo,
            :casa_comercial => producto.casa_comercial,
            :categoria => producto.categoria,
            :iva => producto.hasiva,
            :nombre_generico => producto.nombre_generico
          }
        end
        render :json => @productos 
      }
    end  
  end

  def new
    @producto=  Producto.new
    @producto.ingreso_productos.build
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end
  def show
    respond_to do |format|
      format.js
    end
  end
  def edit
    respond_to do |format|
      format.js{ render "new_or_edit" }
    end
  end

  def create
    @producto = Producto.new(producto_params)
    respond_to do |format|
      if @producto.save
        @productos = Producto.all
        format.html { redirect_to @producto, notice: 'Producto guardado' }
        format.json { render action: 'show', status: :created, location: @producto }
        format.js{
          render "success"
        }
      else
        format.html { render action: 'new' }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
        format.js{
          render "success"
        }
      end
    end
  end

  def update
    respond_to do |format|
      if @producto.update(producto_params)
        @productos = Producto.all
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render action: 'show', status: :created, location: @producto }
        format.js { render "success"}
      else
        format.html { render action: 'edit' }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
        format.js{
          render "success"
        }
      end
    end
  end


  private 
  def producto_params
    params.require(:producto).permit :nombre,
    :nombre_generico,
    :codigo,
    :categoria,
    :casa_comercial,
    :precio_venta,
    :precio_compra,
    :ganancia,
    :hasiva,
    :ingreso_productos_attributes => [
      :lote,
      :cantidad,
      :fecha_caducidad,
      :producto_id,
      :_destroy,
      :id,
    ]                                    
  end  
  def set_producto
      @producto = Producto.find(params[:id])
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	<h3 class="modal-title" id="myModalLabel">Nuevo Producto</h3>
</div>
<%= nested_form_for @producto, :remote => true do |f| %>
<div class="modal-body">
<div class="field">
        <div class="row">
          <div class="col-md-6">
            <%= f.hidden_field :id %>
            <%= f.label :nombre %>
            <%= f.text_field :nombre, :class => "nombre_producto"%>
          </div>
          <div class="col-md-6">
            <%= f.label :nombre_generico, "Nombre Genérico" %>
            <%= f.text_field :nombre_generico %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <%= f.label :codigo, "Código" %>
            <%= f.text_field :codigo %>
          </div>
          <div class="col-md-6">
            <%= f.label :categoria,"Categoría" %>
            <%= f.text_field :categoria%>
          </div>
        </div>
        <%= f.label :casa_comercial %>
        <%= f.text_field :casa_comercial%>
        <div class="row">
          <div class="col-md-4">
            <%= f.label :precio_compra, "Precio de compra" %>
            <%= f.number_field :precio_compra,:class => "precio_compra", :placeholder => "0.00", min: "0", step: "any"%>
          </div>
          <div class="col-md-4">
            <%= f.label :ganancia %>
            <%= f.number_field :ganancia, :placeholder => "0.00", min: "0", :step => "any" %>
          </div>
          <div class="col-md-4 text-center">
            <%= f.label :hasiva, "Tiene IVA?" %>
            <%= f.check_box :hasiva %>
          </div>
        </div>
	<table class="table">
		<thead>
			<tr>
				<th>Fecha Caducidad</th>
				<th>Cantidad</th>
				<th>Lote</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<%= f.fields_for :ingreso_productos, :wrapper => false do |p| %>
				<tr class="fields">
					<%= render "productos/ingresos", p: p %>
				</tr>
			<% end %>
			<tr><td><%= f.link_to_add "Compra", :ingreso_productos, :class => "nuevo_new"%></td>
			</tr>
		</tbody>
	</table>
</div>

</div>
<div class="modal-footer">
	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
	<%= f.submit 'Guardar', class: "btn btn-primary"%>
</div>
<% end %>

app/views/productos/_ingresos.html.erb
<td><%= p.text_field :fecha_caducidad, :class => "datepicker" %></td>
<td><%= p.number_field :cantidad,:class => "cantidad_producto",:placeholder => "0", min: "0"%></td>
<td><%= p.text_field :lote %></td>
<td><%= p.link_to_remove '', :class => "delete_destroy eliminar_item_producto" %></td>

app/views/productos/_productos.html.erb
<table class="data-table table-bordered" data-source="<%= productos_url(format: "json") %>">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Código</th>
      <th>Casa Comercial</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/productos/_show.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h1 class="modal-title" id="myModalLabel">Información</h1>
</div>
<div class="modal-body">
  <p>
    <strong>Nombre:</strong>
    <%= @producto.nombre %>
  </p>
  <p>
    <strong>Nombre genérico:</strong>
    <%= @producto.nombre_generico %>
  </p>
  <p>
    <strong>Categoría:</strong>
    <%= @producto.categoria %>
  </p>
  <p>
    <strong>Código:</strong>
    <%= @producto.codigo %>
  </p>
  <p>
    <strong>Casa comercial:</strong>
    <%= @producto.casa_comercial %>
  </p>
  <p>
    <strong>Precio de compra:</strong>
    <%= @producto.precio_compra %>
  </p>
  <p>
    <strong>Precio de venta:</strong>
    <%= @producto.precio_venta %>
  </p>
  <p>
    <strong>Ganancia:</strong>
    <%= @producto.ganancia %>
  </p>
  <% unless @producto.ingreso_productos.empty? %>
  <legend>Detalles del producto:</legend>
  <table class="table table-hover">
    <thead class= "well">
      <tr>
        <th>Lote</th>
        <th>Cantidad</th>
        <th>Fecha de caducidad</th>
      </tr>
    </thead>
    <tbody>
      <% @producto.ingreso_productos.each do |detalle| %>
      <% unless detalle.cantidad == 0 %>
      <tr>
        <td><%= detalle.lote %></td>
        <td><%= detalle.cantidad %></td>
        <td><%= detalle.fecha_caducidad %></td>
      </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <% end %>  
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-default" data-dismiss="modal">Salir</button>
  <%= link_to 'Editar', edit_producto_path(producto), {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal', class: "editar_edit"}%>
</div>

app/views/productos/index.html.erb
<%= link_to 'Nuevo', {:controller => 'productos', :action => 'new'},  {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#myModal', class: "nuevo_new"}  %>
<h1 class="text-center">LISTA DE PRODUCTOS</h1>

<div class="table-responsive table-productos">
  <%= render "productos", productos: @productos %>  
</div>

app/views/productos/new_or_edit.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'form', locals: {producto: @producto}) %>');
window.Helpers.ButtonsHelper.init();
window.Helpers.FormsHelper.init()
window.Helpers.Datepicker.init_datepicker();

app/views/productos/show.js.erb
m = $('#content_modal');
m.html('<%= j(render partial: 'show', locals: {producto: @producto}) %>');

app/views/productos/success.js.erb
<%- if @producto.errors.any? %>
  $('#content_modal').html('<%= escape_javascript(render('form')) %>');
  window.Helpers.ButtonsHelper.init();
  window.Helpers.FormsHelper.init()
  <%- @producto.errors.full_messages.each do |msg|%>
    alertify.error("<%=j msg %>");
  <%- end %>
<%- else %>
  $("#myModal").modal("hide");
  $('body').removeClass('modal-open');
  $('.modal-backdrop').remove();
  $(".table-productos").html('<%= j render 'productos', productos: @productos %>');
  window.Helpers.init_datatables();
  window.Helpers.ButtonsHelper.init();
  alertify.success("Producto guardado");
<%- end %>